version: "2"
services:

  server:
    container_name: nodered
    build: build
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
      nproc: 65535
    ports:
      - "1880:1880"
    volumes:
      - data:/home/nodered/data

volumes:
  data:
    driver: local
