version: "2"
services:

  noderedimage:
    container_name: nodered
    build: build
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
      nproc: 65535
    ports:
      - "1880:1880"
    volumes:
      - data:/nodered_data
    networks:
      - front

volumes:
  data:
    driver: local

networks:
  front:
    driver: bridge
